---

 - hosts: all
   become: true
   roles:
     - base

 - hosts: web_servers
   become: true
   roles:
     - web_servers

 - hosts: db_servers
   become: true
   roles:
     - db_servers

 - hosts: file_servers
   become: true
   roles:
     - file_servers


 - hosts: 192.168.1.139
   tasks:
    - name: kopieer index.php naar de Apache-server
      copy:
        src: index.php
        dest: /var/www/html/
        mode: 0644

    - name: kopieer testpagina.php naar de Apache-server
      copy:
        src: testpagina.php
        dest: /var/www/html/
        mode: 0644


